### ISSUE TITLE
`std::thread::sleep` in async functions

### ISSUE THREAD

**Issue by RoDmitry** [Arthurdw/firefly#11]
https://github.com/Arthurdw/firefly/blob/c7d488dba57ef307f0c9402c52325d40584922c9/server/src/database.rs#L207C29-L207C29

This function is blocking, and should not be used in async functions. ([docs](https://doc.rust-lang.org/std/thread/fn.sleep.html))

You should use async sleep `tokio::time::sleep`, otherwise your whole thread is unavailable.

**Comment by Arthurdw** [comment]
Hey there, thanks for reaching out. I will resolve this issue tomorrow.
