### ISSUE TITLE
Docker image arthurdw/firefly is no accessible - autoclosed

### ISSUE THREAD

**Issue by BarbossHack** [Arthurdw/firefly#3]
Docker image arthurdw/firefly seems to be private on dockerhub

If I visit https://hub.docker.com/repository/docker/arthurdw/firefly I am redirected to the dockerhub login page

**Comment by Arthurdw** [comment]
My docker hub says it's public tho :/
Cuz like I can make it private.

![image](https://user-images.githubusercontent.com/38541241/184818048-5edd5a6d-a9ac-4f46-8a39-e2f181bb22df.png)

It's my first time publishing a docker image, so I'll probably have done smth wrong.

**Comment by BarbossHack** [comment]
I've never pushed an image to dockerhub sry (but still doesn't work for now)

**Comment by Arthurdw** [comment]
No problem, @BarbossHack can you try this URL?  
[https://hub.docker.com/r/arthurdw/firefly](https://hub.docker.com/r/arthurdw/firefly)

**Comment by BarbossHack** [comment]
Yeah with this URL it works :+1:

So the fact I have a "408 request timeout" when pulling the image is a problem on my side, sorry

(you can update the README with the good url)

**Comment by Arthurdw** [comment]
No problem, I'll indeed update the link in the README, thanks for lmk ♥
