### ISSUE TITLE
Unnecessary manual drop/free

### ISSUE THREAD

**Issue by Sculas** [Arthurdw/firefly#4]
Rust should drop the stream automatically at that point, since it's no longer being referenced after.
https://github.com/Arthurdw/firefly/blob/275c66d9e60a79406a1ba3852b7257a6fc24c852/ffly-rs/src/lib.rs#L96-L101

**Comment by Arthurdw** [comment]
Has been resolved in [`fa78e81`](https://github.com/Arthurdw/firefly/commit/fa78e8110dca30a348ee512e3a27569fc2de6dd4), will be in the next patch of the lib. Thanks for your note ♥
